import math

FPS = 60  # А может 59.98?
WIDTH, HEIGHT = 1440, 960  # Весь экран
BUTTON_WIDTH, BUTTON_HEIGHT = 200, 50
START_BUTTON_X, START_BUTTON_Y = 50, 300

GRAVITY_POWER = 20

CELL_SIZE = 20

MAP_SIZE = 35


MIN_Z = 10
MAX_Z = 100
PLAYER_COORDS = (MAP_SIZE // 2, MAP_SIZE // 2)
RADIUS_WITHOUT_TARGET = 1

MAX_PERSENT_FIELD_OCCUPANCY = 0.6
#
START_CAN_USE_CELLS = []
RESERVED_CELLS = []


MIN_HEIGHT_ANGLE = -math.pi / 6
MAX_HEIGHT_ANGLE = math.pi / 3

FOV_HALF_WIDTH = math.pi / 6
FOV_HALF_HEIGHT = math.pi / 9

FOV_INACCURACY = math.pi / 36

COEF_MOVE_ANGLE = 300
